# 학습 목표
- 데이터를 다룰 때 다양한 활용 방법을 이해할 수 있다.
- 조건문을 활용하여 실제 값을 다른값으로 처리할 수 있다.
- 데이터에 중복이 있을경우 중복을 제거할 수 있다.

# 학습 준비

In [1]:
import os
import pandas as pd 
from pandasql import sqldf
mysql = lambda q: sqldf(q, globals())

data_dir = './data/'

bike = pd.read_csv(os.path.join(data_dir, 'bike_dataset.csv'))
orders = pd.read_csv(os.path.join(data_dir, 'orders.csv'))
customers = pd.read_csv(os.path.join(data_dir, 'customers.csv'))
employees = pd.read_csv(os.path.join(data_dir,'employees.csv'))
ds_2020 = pd.read_csv(os.path.join(data_dir, 'DS_JobsSalaries_2020.csv'))
ds_2021 = pd.read_csv(os.path.join(data_dir, 'DS_JobsSalaries_2021.csv'))

# 특정 데이터 조건과 별칭

## 특정 데이터 조건주기(LIKE, Wildcard)
### LIKE
- 조회 조건 값이 명확하지 않을 때 특정 내용을 찾을 수 있다.
- 조건에 문자나 숫자를 포함할 수 있다.
- 주로 Wildcard와 함께 사용한다.

### Wildcard
- `%` : 조건을 포함하는 모든 문자를 의미합니다. (0개 이상의 문자)
- `_` : 한 글자를 의미합니다.
    - `_`의 개수에 따라 뒤에 오는 문자열의 개수를 정할 수 있습니다.
    - 예: `to_`라고 지정하면 `tom`은 추출되지만 `tomi`는 추출되지 않습니다.

In [2]:
# hr이 0이고, weekday에 'ur'이란 단어가 들어간 데이터를 추출

mysql("""

SELECT *
FROM bike
WHERE hr = 0
AND weekday LIKE '%ur%'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-06,spring,2011,Jan,0,0,Thursday,1,Clear,0.18,0.2424,0.55,0.0000,0,11,11
2,2011-01-08,spring,2011,Jan,0,0,Saturday,0,Cloudy,0.18,0.1970,0.51,0.1642,1,24,25
3,2011-01-13,spring,2011,Jan,0,0,Thursday,1,Clear,0.14,0.1212,0.59,0.2836,1,6,7
4,2011-01-15,spring,2011,Jan,0,0,Saturday,0,Clear,0.18,0.2424,0.55,0.0000,3,25,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,2012-12-15,winter,2012,Dec,0,0,Saturday,0,Clear,0.30,0.3333,0.70,0.0000,4,90,94
204,2012-12-20,winter,2012,Dec,0,0,Thursday,1,Clear,0.32,0.3333,0.61,0.1343,2,40,42
205,2012-12-22,spring,2012,Dec,0,0,Saturday,0,Clear,0.26,0.2121,0.44,0.5821,1,30,31
206,2012-12-27,spring,2012,Dec,0,0,Thursday,1,LightRain,0.26,0.2273,0.87,0.2985,0,3,3
207,2012-12-29,spring,2012,Dec,0,0,Saturday,0,Cloudy,0.24,0.2424,0.70,0.0000,1,25,26

In [ ]:
# hr이 0이고, weathersit이 'Cl'로 시작하는 데이터를 추출

mysql("""

SELECT *
FROM bike
WHERE hr = 0
      AND weathersit LIKE 'Cl%'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-02,spring,2011,Jan,0,0,Sunday,0,Cloudy,0.46,0.4545,0.88,0.2985,4,13,17
2,2011-01-03,spring,2011,Jan,0,0,Monday,1,Clear,0.22,0.1970,0.44,0.3582,0,5,5
3,2011-01-04,spring,2011,Jan,0,0,Tuesday,1,Clear,0.16,0.1818,0.55,0.1045,0,5,5
4,2011-01-05,spring,2011,Jan,0,0,Wednesday,1,Clear,0.20,0.2576,0.64,0.0000,0,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669,2012-12-26,spring,2012,Dec,0,0,Wednesday,1,Cloudy,0.28,0.2727,0.65,0.2537,1,8,9
670,2012-12-28,spring,2012,Dec,0,0,Friday,1,Cloudy,0.24,0.2424,0.60,0.1642,3,22,25
671,2012-12-29,spring,2012,Dec,0,0,Saturday,0,Cloudy,0.24,0.2424,0.70,0.0000,1,25,26
672,2012-12-30,spring,2012,Dec,0,0,Sunday,0,Cloudy,0.26,0.2576,0.60,0.1642,0,41,41
673,2012-12-31,spring,2012,Dec,0,0,Monday,1,Clear,0.18,0.1818,0.55,0.1940,4,30,34

In [5]:
# hr이 0이고, mnth이 'ma?'인 데이터를 확인

mysql("""

SELECT *
FROM bike
WHERE hr = 0
      AND mnth LIKE 'ma_'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-03-01,spring,2011,Mar,0,0,Tuesday,1,Clear,0.30,0.2727,0.70,0.4627,0,7,7
1,2011-03-02,spring,2011,Mar,0,0,Wednesday,1,Clear,0.22,0.2273,0.69,0.1642,3,5,8
2,2011-03-03,spring,2011,Mar,0,0,Thursday,1,Clear,0.24,0.1970,0.30,0.4627,3,10,13
3,2011-03-04,spring,2011,Mar,0,0,Friday,1,Cloudy,0.20,0.1970,0.55,0.1940,0,12,12
4,2011-03-05,spring,2011,Mar,0,0,Saturday,0,Cloudy,0.28,0.2879,0.81,0.1045,4,15,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2012-05-27,summer,2012,May,0,0,Sunday,0,Cloudy,0.68,0.6364,0.69,0.1642,48,89,137
120,2012-05-28,summer,2012,May,0,1,Monday,0,Clear,0.62,0.5758,0.83,0.2239,21,44,65
121,2012-05-29,summer,2012,May,0,0,Tuesday,1,Clear,0.70,0.6667,0.79,0.1940,12,33,45
122,2012-05-30,summer,2012,May,0,0,Wednesday,1,LightRain,0.64,0.5758,0.89,0.1045,4,32,36
123,2012-05-31,summer,2012,May,0,0,Thursday,1,Clear,0.64,0.6061,0.69,0.1343,13,48,61

In [6]:
# hr이 0이고, mnth이 'ma?'이며 weekday에 'ur'이란 단어가 들어간 데이터를 추출

mysql(""" 

SELECT *
FROM bike
WHERE hr = 0
      AND mnth LIKE 'ma_'
      AND weekday LIKE '%ur%'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-03-03,spring,2011,Mar,0,0,Thursday,1,Clear,0.24,0.1970,0.30,0.4627,3,10,13
1,2011-03-05,spring,2011,Mar,0,0,Saturday,0,Cloudy,0.28,0.2879,0.81,0.1045,4,15,19
2,2011-03-10,spring,2011,Mar,0,0,Thursday,1,LightRain,0.34,0.3182,0.00,0.2537,3,0,3
3,2011-03-12,spring,2011,Mar,0,0,Saturday,0,Clear,0.26,0.2727,0.60,0.1343,4,30,34
4,2011-03-17,spring,2011,Mar,0,0,Thursday,1,Clear,0.38,0.3939,0.66,0.2537,4,19,23
5,2011-03-19,spring,2011,Mar,0,0,Saturday,0,Cloudy,0.60,0.6212,0.53,0.2537,26,50,76
6,2011-03-24,summer,2011,Mar,0,0,Thursday,1,Cloudy,0.32,0.3030,0.93,0.2239,0,11,11
7,2011-03-26,summer,2011,Mar,0,0,Saturday,0,Cloudy,0.26,0.2424,0.38,0.2836,3,25,28
8,2011-03-31,summer,2011,Mar,0,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2239,0,3,3
9,2011-05-05,summer,2011,May,0,0,Thursday,1,Clear,0.36,0.3485,0.66,0.1940,4,23,27
10,2011-05-07,summer,2011,May,0,0,Saturday,0,Clear,0.42,0.4242,0.82,0.1343,10,76,86
11,2011-05-12,summer,2011,May,0,0,Thursday,1,Cloudy,0.46,0.4545,0.88,0.2239,5,39,44
12,2011-05-14,summer,2011,May,0,0,Saturday,0,Cloudy,0.50,0.4848,0.88,0.1343,24,78,102
13,2011-05-19,summer,2011,May,0,0,Thursday,1,Clear,0.52,0.5000,0.94,0.1045,6,23,29
14,2011-05-21,summer,2011,May,0,0,Saturday,0,Clear,0.52,0.5000,0.77,0.1045,20,78,98
15,2011-05-26,summer,2011,May,0,0,Thursday,1,Clear,0.64,0.6061,0.73,0.1343,11,34,45
16,2011-05-28,summer,2011,May,0,0,Saturday,0,Clear,0.58,0.5455,0.88,0.1343,15,79,94
17,2012-03-01,spring,2012,Mar,0,0,Thursday,1,Cloudy,0.42,0.4242,0.94,0.0000,1,10,11
18,2012-03-03,spring,2012,Mar,0,0,Saturday,0,LightRain,0.36,0.3636,0.93,0.0896,1,21,22
19,2012-03-08,spring,2012,Mar,0,0,Thursday,1,Clear,0.44,0.4394,0.62,0.3284,11,35,46
20,2012-03-10,spring,2012,Mar,0,0,Saturday,0,Clear,0.30,0.2727,0.36,0.3582,9,68,77
21,2012-03-15,spring,2012,Mar,0,0,Thursday,1,Clear,0.54,0.5152,0.49,0.1343,14,46,60
22,2012-03-17,spring,2012,Mar,0,0,Saturday,0,Cloudy,0.44,0.4394,0.94,0.0896,13,87,100
23,2012-03-22,summer,2012,Mar,0,0,Thursday,1,Clear,0.52,0.5000,0.83,0.0896,9,32,41
24,2012-03-24,summer,2012,Mar,0,0,Saturday,0,Clear,0.58,0.5455,0.68,0.0000,45,111,156
25,2012-03-29,summer,2012,Mar,0,0,Thursday,1,Clear,0.54,0.5152,0.68,0.1940,10,38,48
26,2012-03-31,summer,2012,Mar,0,0,Saturday,0,Clear,0.38,0.3939,0.82,0.1940,12,80,92
27,2012-05-03,summer,2012,May,0,0,Thursday,1,Cloudy,0.48,0.4697,0.82,0.2239,15,75,90
28,2012-05-05,summer,2012,May,0,0,Saturday,0,Clear,0.60,0.5606,0.83,0.0000,42,111,153
29,2012-05-10,summer,2012,May,0,0,Thursday,1,LightRain,0.50,0.4848,0.77,0.1642,2,31,33
30,2012-05-12,summer,2012,May,0,0,Saturday,0,Clear,0.52,0.5000,0.42,0.1642,25,111,136
31,2012-05-17,summer,2012,May,0,0,Thursday,1,Clear,0.60,0.5758,0.78,0.1343,30,49,79
32,2012-05-19,summer,2012,May,0,0,Saturday,0,Clear,0.52,0.5000,0.48,0.1045,30,118,148
33,2012-05-24,summer,2012,May,0,0,Thursday,1,Clear,0.60,0.5606,0.83,0.0896,7,49,56
34,2012-05-26,summer,2012,May,0,0,Saturday,0,Clear,0.64,0.5758,0.83,0.1642,18,98,116
35,2012-05-31,summer,2012,May,0,0,Thursday,1,Clear,0.64,0.6061,0.69,0.1343,13,48,61

### 별칭 사용하기(Alias)
- 임시로 컬럼명 변경시 별칭 사용
- 별칭은 컬럼명 바로 뒤 작성
- 컬럼명과 별칭 사이에는 `AS`를 작성 `AS`는 생략가능
- 특수문자, 대소문자, 공백 사용하려면 `""` 또는 `''`로 묶어줘야한다.
- `SELECT`, `FROM` 절에서 사용
- 뒷부분에서 나올 조인과 서브쿼리에서 테이블과 서브쿼리를 호출하기 위해 **필수로 사용**

In [ ]:
# emp와 hum를 추출하고 hum에 'humidity'란 별칭주기

mysql("""

SELECT temp, hum AS 'humidity'
FROM bike
LIMIT 5

""")

   temp  humidity
0  0.24      0.81
1  0.22      0.80
2  0.22      0.80
3  0.24      0.75
4  0.24      0.75

In [8]:
# bike테이블 이름을 'b'로 지정, b 테이블의 temp와 hum를 추출

mysql(""" 

SELECT b.temp, b.hum AS 'humidity'
FROM bike AS b
LIMIT 5

""")

   temp  humidity
0  0.24      0.81
1  0.22      0.80
2  0.22      0.80
3  0.24      0.75
4  0.24      0.75

#  데이터 정렬과 중복 제거
## 데이터 정렬하기(ORDER BY)
- SQL 구문 하단에 작성
- 데이터 추출시, 테이블에 입력된 순서대로 출력되는 것이 기본
- 데이터가 오름차순, 내림차순으로 정렬된 형태가 필요할 때가 있다.
- 오름차순 : 컬럼명 뒤 ASC 적기, ASC를 생략해도 기본으로 오름차순으로 정렬됨
- 내림차순 : 컬럼명 뒤 DESC 적기
- SELECT 구분에 지정한 컬럼의 순서를 숫자로 입력해도 실행 가능

In [9]:
# dteday, temp, cnt 컬럼을 추출하고, cnt가 높은 순서대로 100개만 정렬 
# 순서가 같은경우 temp가 낮은 순서대로 정렬됨

mysql("""

SELECT dteday, temp, cnt
FROM bike
ORDER BY cnt DESC, temp
LIMIT 100

""")

        dteday  temp  cnt
0   2012-09-12  0.66  977
1   2012-09-20  0.64  976
2   2012-09-11  0.70  970
3   2012-09-10  0.62  968
4   2012-09-25  0.66  967
..         ...   ...  ...
95  2012-06-11  0.80  831
96  2012-03-23  0.70  830
97  2012-07-11  0.80  830
98  2012-10-11  0.50  827
99  2012-05-31  0.76  827

[100 rows x 3 columns]

In [10]:
# 이번에는 컬럼 순서를 입력하여 정렬

mysql("""

SELECT dteday, temp, cnt
FROM bike
ORDER BY 3 DESC, 2
LIMIT 100

""")

        dteday  temp  cnt
0   2012-09-12  0.66  977
1   2012-09-20  0.64  976
2   2012-09-11  0.70  970
3   2012-09-10  0.62  968
4   2012-09-25  0.66  967
..         ...   ...  ...
95  2012-06-11  0.80  831
96  2012-03-23  0.70  830
97  2012-07-11  0.80  830
98  2012-10-11  0.50  827
99  2012-05-31  0.76  827

[100 rows x 3 columns]

## 중복제거하기(DISTINCT)
- 출력에서 고유한 값을 반환기 위한 키워드
- `DISTINCT`는 옆에 온 모든 컬럼을 고려해 중복을 제거함
- 뒤에서 매울 집계함수에도 사용할 수 있다.

In [11]:
# weekday, weathersit 컬럼에서 중복을 제거

mysql(""" 

SELECT DISTINCT weekday, weathersit
FROM bike

""")

      weekday         weathersit
0    Saturday              Clear
1    Saturday             Cloudy
2    Saturday          LightRain
3      Sunday             Cloudy
4      Sunday          LightRain
5      Sunday              Clear
6      Monday              Clear
7     Tuesday              Clear
8     Tuesday             Cloudy
9   Wednesday              Clear
10   Thursday              Clear
11   Thursday             Cloudy
12     Friday             Cloudy
13     Friday          LightRain
14     Friday              Clear
15     Monday             Cloudy
16    Tuesday          LightRain
17  Wednesday             Cloudy
18     Monday          LightRain
19  Wednesday          LightRain
20  Wednesday  Snow_Thunderstorm
21   Thursday          LightRain
22   Saturday               None
23     Monday  Snow_Thunderstorm
24   Saturday  Snow_Thunderstorm

In [12]:
# yr, weekday, weathersit 컬럼에서 중복을 제거

mysql(""" 

SELECT DISTINCT yr, weekday, weathersit
FROM bike


""")

      yr    weekday         weathersit
0   2011   Saturday              Clear
1   2011   Saturday             Cloudy
2   2011   Saturday          LightRain
3   2011     Sunday             Cloudy
4   2011     Sunday          LightRain
5   2011     Sunday              Clear
6   2011     Monday              Clear
7   2011    Tuesday              Clear
8   2011    Tuesday             Cloudy
9   2011  Wednesday              Clear
10  2011   Thursday              Clear
11  2011   Thursday             Cloudy
12  2011     Friday             Cloudy
13  2011     Friday          LightRain
14  2011     Friday              Clear
15  2011     Monday             Cloudy
16  2011    Tuesday          LightRain
17  2011  Wednesday             Cloudy
18  2011     Monday          LightRain
19  2011  Wednesday          LightRain
20  2011  Wednesday  Snow_Thunderstorm
21  2011   Thursday          LightRain
22  2011   Saturday               None
23  2012     Sunday              Clear
24  2012     Sunday             Cloudy
25  2012     Sunday          LightRain
26  2012     Monday              Clear
27  2012     Monday             Cloudy
28  2012    Tuesday              Clear
29  2012  Wednesday              Clear
30  2012  Wednesday             Cloudy
31  2012   Thursday             Cloudy
32  2012   Thursday              Clear
33  2012     Friday              Clear
34  2012     Friday             Cloudy
35  2012   Saturday              Clear
36  2012   Saturday             Cloudy
37  2012     Monday          LightRain
38  2012     Monday  Snow_Thunderstorm
39  2012    Tuesday             Cloudy
40  2012  Wednesday          LightRain
41  2012   Thursday          LightRain
42  2012     Friday          LightRain
43  2012    Tuesday          LightRain
44  2012   Saturday          LightRain
45  2012   Saturday  Snow_Thunderstorm

# 조건문 활용하기(IF, CASE WHEN ~ THEN ~)
## IF(조건, 참일 때 반환 값, 거짓일 때 반환 값)
- 단일 조건문
- 엑셀의 `IF`함수와 동일한 역할
- SELECT, WHERE 절에서 사용 가능
- IF 내에 조건을 줄 떄 함수와 함께 사용 가능
- 참고 : pandasql에서는 if함수를 iif로 표현

In [13]:
# 1990년 이전과 이후에 태어난 고객 분리하기
# 이해하기 쉽게 '고객명', '생년월일', '1990년 기준'이라는 별칭 사용

mysql("""
 
SELECT customerName AS "고객명", 
      birthday AS "생년월일", 
      iif(birthday >= '1990-01-01' , '이후', '이전') AS "1990년 기준"
FROM customers

""")

                        고객명          생년월일 1990년 기준
0             Unai Bustinza    1992. 2. 2       이후
1              Igor Bubnjic   1992. 7. 17       이후
2               Gideon Jung   1994. 9. 12       이후
3          Alberto Aquilani    1984. 7. 7       이전
4         Nicola Strambelli    1988. 9. 6       이전
..                      ...           ...      ...
118     Jeroen Vanthournout   1989. 6. 29       이전
119            Raul Rusescu    1988. 7. 9       이전
120  Konstantinos Fortounis  1992. 10. 16       이후
121                    Sami  1988. 12. 18       이전
122         Szymon Drewniak   1993. 7. 11       이후

[123 rows x 3 columns]

## CASE WHEN ~ THEN
- 다중 조건문
- 조건에 따른 값을 다르게 출력하고 싶을 때 사용
- 조건에 따라 기존에 있는 컬럼을 이용해 새로운 컬럼을 만들기도 함
- 작성순서
``` sql
CASE WHEN '조건1' THEN '조건1 반환값' 
     WHEN '조건2' THEN '조건2 반환값' 
     ELSE '만족하는 조건이 없을 때 반환 값'
     END
```

- CASE문은 WHEN의 조건을 순차적으로 체크하고 조건이 충족되면 THEN에 명시된 값을 반환
    - WHEN과 THEN은 한 쌍으로 존재합니다.
    - WHEN과 THEN은 여러 개가 존재할 수 있습니다.
    - ELSE는 앞의 조건들에 모두 해당하지 않았을 때 정해줄 기본 값입니다.
    - ELSE가 없고 조건에 맞는 값이 없으면 NULL값을 반환합니다.
- CASE WHEN, THEN, END를 먼저 작성한 후에 조건을 적으면 문법 실수를 줄일 수 있다.

In [14]:
# 고객 한도를 5만원, 십만원 단위로 분리하기
mysql("""
SELECT customerName, creditLimit,
      CASE WHEN creditLimit <= 50000 THEN '5만원이하'
      WHEN creditLimit <= 100000 THEN '10만원이하'
      ELSE '10만원초과'
      END AS '고객한도분리'
FROM customers

""")

               customerName  creditLimit  고객한도분리
0             Unai Bustinza        21000   5만원이하
1              Igor Bubnjic        71800  10만원이하
2               Gideon Jung       117300  10만원초과
3          Alberto Aquilani       118200  10만원초과
4         Nicola Strambelli        81700  10만원이하
..                      ...          ...     ...
118     Jeroen Vanthournout        60300  10만원이하
119            Raul Rusescu        43300   5만원이하
120  Konstantinos Fortounis        85100  10만원이하
121                    Sami       110000  10만원초과
122         Szymon Drewniak        88900  10만원이하

[123 rows x 3 columns]

# 데이터 타입 변환하기(CAST)
## CAST
- 데이터의 타입을 변환하는 함수
- 작성순서
```sql
CAST (컬럼 AS 변환할 타입)
```
- 변환할 타입에는 int, float, varchar, datetime 등이 있다.

In [ ]:
# 데이터 bike의 정보를 확인
# 현재 yr은 int 타입

bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      17379 non-null  object
 1   season      17379 non-null  object
 2   yr          17379 non-null  int64
 3   mnth        17379 non-null  object
 4   hr          17379 non-null  int64
 5   holiday     17379 non-null  int64
 6   weekday     17379 non-null  object
 7   workingday  17379 non-null  int64
 8   weathersit  17378 non-null  object
 9   temp        17379 non-null  float64
 10  atemp       17379 non-null  float64
 11  hum         17379 non-null  float64
 12  windspeed   17379 non-null  float64
 13  casual      17379 non-null  int64
 14  registered  17379 non-null  int64
 15  cnt         17379 non-null  int64
dtypes: float64(4), int64(7), object(5)
memory usage: 2.1+ MB

In [16]:
# 먼저 2011년 데이터 5개만 추출

mysql("""
SELECT *
FROM bike
WHERE yr = 2011 
LIMIT 5
""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0,0,1,1

In [17]:
# 현재 int 타입인 yr을 varchar 타입으로 변경

mysql("""
SELECT CAST(yr AS varchar) AS yr
FROM bike
LIMIT 5
""")

     yr
0  2011
1  2011
2  2011
3  2011
4  2011

In [18]:
# yr을 문자열타입으로 변환한 후 2011년 데이터 5개만 추출
# [참고] 보통 해당 타입을 지정하지 않으면 에러가 나지만 데이터베이스 시스템에 따라 타입에 상관 없이 데이터를 추출할 수 있다.

mysql("""
SELECT CAST(yr AS varchar) AS yr
FROM bike
WHERE CAST(yr AS varchar) = '2011'
LIMIT 5
""")

     yr
0  2011
1  2011
2  2011
3  2011
4  2011