# 학습 목표

- SQL을 이용해 테이블을 지정하여(FROM) 데이터를 조회(SELECT)하는 쿼리의 기본 뼈대를 만드는 방법을 활용할 수 있다.
- DB에 저장된 수많은 데이터에 조건을 주어 데이터를 필터링할 수 있다.
- 특정 필드에 대한 데이터를 정렬할 수 있다.
- 여러 연산자를 통해 데이터에 세부적으로 조건을 주는 방법을 활용할 수 있다.

# 데이터불러오기

In [1]:
pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in c:\users\nini\anaconda3\lib\site-packages (from pandasql) (1.26.4)
Requirement already satisfied: pandas in c:\users\nini\anaconda3\lib\site-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in c:\users\nini\anaconda3\lib\site-packages (from pandasql) (2.0.34)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nini\anaconda3\lib\site-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nini\anaconda3\lib\site-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nini\anaconda3\lib\site-packages (from pandas->pandasql) (2023.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nini\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (4.14.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\nini\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (3.0.1)
Requirement already satisfied: six>=1.5 in c:\users\nini\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py): started
  Building wheel for pandasql (setup.py): finished with status 'done'
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26801 sha256=bf32378643cb4daca0fd4077992f4f542bc389770b645aaaeb81a87b4fb98958
  Stored in directory: c:\users\nini\appdata\local\pip\cache\wheels\15\a1\e7\6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3
Note: you may need to restart the kernel to use updated packages.

In [3]:
# 데이터가 잘 불러와지는지 확인하기

import os 
import pandas as pd 
from pandasql import sqldf
# pandasql을 전역 환경으로 지정
mysql = lambda q: sqldf(q, globals())

data_dir = './data/'

bike = pd.read_csv(os.path.join(data_dir, 'bike_dataset.csv'))
orders = pd.read_csv(os.path.join(data_dir, 'orders.csv'))
customers = pd.read_csv(os.path.join(data_dir, 'customers.csv'))
employees = pd.read_csv(os.path.join(data_dir,'employees.csv'))
ds_2020 = pd.read_csv(os.path.join(data_dir, 'DS_JobsSalaries_2020.csv'))
ds_2021 = pd.read_csv(os.path.join(data_dir, 'DS_JobsSalaries_2021.csv'))

print("데이터 준비 완료!")

데이터 준비 완료!

# 쿼리문 작성과 데이터 필터링

## 쿼리문 작성하기(SELECT, FROM)
전체 컬럼 조회하기
- SELECT 구문에 * 기호를 사용하면 해당 테이블의 모든 컬럼을 조회할 수 있다.

In [4]:
# bike 테이블에서 전체 컬럼 조회하기
mysql("""

SELECT * 
FROM bike

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,spring,2012,Dec,19,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,11,108,119
17375,2012-12-31,spring,2012,Dec,20,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,8,81,89
17376,2012-12-31,spring,2012,Dec,21,0,Monday,1,Clear,0.26,0.2576,0.60,0.1642,7,83,90
17377,2012-12-31,spring,2012,Dec,22,0,Monday,1,Clear,0.26,0.2727,0.56,0.1343,13,48,61
17378,2012-12-31,spring,2012,Dec,23,0,Monday,1,Clear,0.26,0.2727,0.65,0.1343,12,37,49

In [5]:
# bike테이블에서 날짜, 계절, 날씨 컬럼을 추출

mysql("""

SELECT dteday, season, weathersit
FROM bike

""")

           dteday  season weathersit
0      2011-01-01  spring      Clear
1      2011-01-01  spring      Clear
2      2011-01-01  spring      Clear
3      2011-01-01  spring      Clear
4      2011-01-01  spring      Clear
...           ...     ...        ...
17374  2012-12-31  spring     Cloudy
17375  2012-12-31  spring     Cloudy
17376  2012-12-31  spring      Clear
17377  2012-12-31  spring      Clear
17378  2012-12-31  spring      Clear

[17379 rows x 3 columns]

## 전체 데이터 필터링하기(WHERE)

- SQL에서 쿼리 결과 필터링은 중요한 기술입니다.
- WHERE는 FROM절 다음에 위치합니다.
- WHERE절에는 연산자를 같이 사용해야 합니다.

In [6]:
# 2012년을 기준으로 데이터를 확인하기

mysql("""

SELECT *
FROM bike
WHERE yr = 2012

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2012-01-01,spring,2012,Jan,0,0,Sunday,0,Clear,0.36,0.3788,0.66,0.0000,5,43,48
1,2012-01-01,spring,2012,Jan,1,0,Sunday,0,Clear,0.36,0.3485,0.66,0.1343,15,78,93
2,2012-01-01,spring,2012,Jan,2,0,Sunday,0,Clear,0.32,0.3485,0.76,0.0000,16,59,75
3,2012-01-01,spring,2012,Jan,3,0,Sunday,0,Clear,0.30,0.3333,0.81,0.0000,11,41,52
4,2012-01-01,spring,2012,Jan,4,0,Sunday,0,Clear,0.28,0.3030,0.81,0.0896,0,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8729,2012-12-31,spring,2012,Dec,19,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,11,108,119
8730,2012-12-31,spring,2012,Dec,20,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,8,81,89
8731,2012-12-31,spring,2012,Dec,21,0,Monday,1,Clear,0.26,0.2576,0.60,0.1642,7,83,90
8732,2012-12-31,spring,2012,Dec,22,0,Monday,1,Clear,0.26,0.2727,0.56,0.1343,13,48,61
8733,2012-12-31,spring,2012,Dec,23,0,Monday,1,Clear,0.26,0.2727,0.65,0.1343,12,37,49

# 비교 연산자 사용하기
- 비교 연산자는 SQL 구문에서 필수적이다.
- 아래의 표 이미지 참고    
    
 ![image.png](./images/2.png)

In [7]:
# 비교 연산자 =
# 2012년을 기준으로 날짜, 계절, 날씨 컬럼을 확인해 봅시다. LIMIT은 전체 데이터 중 100개만 확인

mysql("""  

SELECT dteday, season, weathersit
FROM bike
WHERE yr = 2012
LIMIT 100    

""")

        dteday  season weathersit
0   2012-01-01  spring      Clear
1   2012-01-01  spring      Clear
2   2012-01-01  spring      Clear
3   2012-01-01  spring      Clear
4   2012-01-01  spring      Clear
..         ...     ...        ...
95  2012-01-05  spring     Cloudy
96  2012-01-05  spring      Clear
97  2012-01-05  spring      Clear
98  2012-01-05  spring      Clear
99  2012-01-05  spring     Cloudy

[100 rows x 3 columns]

In [8]:
# =는 '같다'는 의미로 사용될 수도 있다.
# 계절이 봄인 전체 데이터 확인하기

mysql("""

SELECT *
FROM bike
WHERE season = 'spring'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4237,2012-12-31,spring,2012,Dec,19,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,11,108,119
4238,2012-12-31,spring,2012,Dec,20,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,8,81,89
4239,2012-12-31,spring,2012,Dec,21,0,Monday,1,Clear,0.26,0.2576,0.60,0.1642,7,83,90
4240,2012-12-31,spring,2012,Dec,22,0,Monday,1,Clear,0.26,0.2727,0.56,0.1343,13,48,61
4241,2012-12-31,spring,2012,Dec,23,0,Monday,1,Clear,0.26,0.2727,0.65,0.1343,12,37,49

In [9]:
# 비교 연산자 != 또는 <>
# 특정 데이터를 제외하여 선택할 때 사용
# 계절이 봄이 아닌 전체 데이터를 확인

mysql("""  

SELECT *
FROM bike
WHERE season != 'spring'
""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-03-21,summer,2011,Mar,0,0,Monday,1,LightRain,0.34,0.3030,0.66,0.3881,2,11,13
1,2011-03-21,summer,2011,Mar,1,0,Monday,1,Cloudy,0.34,0.3030,0.71,0.3881,1,6,7
2,2011-03-21,summer,2011,Mar,2,0,Monday,1,Cloudy,0.34,0.3030,0.71,0.3284,1,5,6
3,2011-03-21,summer,2011,Mar,3,0,Monday,1,Cloudy,0.34,0.3030,0.71,0.3284,0,1,1
4,2011-03-21,summer,2011,Mar,5,0,Monday,1,Clear,0.32,0.3030,0.81,0.2985,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13132,2012-12-20,winter,2012,Dec,19,0,Thursday,1,LightRain,0.34,0.3182,0.71,0.2537,3,115,118
13133,2012-12-20,winter,2012,Dec,20,0,Thursday,1,LightRain,0.34,0.3333,0.76,0.1642,1,49,50
13134,2012-12-20,winter,2012,Dec,21,0,Thursday,1,LightRain,0.34,0.3333,0.76,0.1642,1,25,26
13135,2012-12-20,winter,2012,Dec,22,0,Thursday,1,LightRain,0.34,0.3333,0.87,0.1940,1,20,21
13136,2012-12-20,winter,2012,Dec,23,0,Thursday,1,LightRain,0.40,0.4091,0.82,0.2985,0,13,13

In [10]:
# <> 연산자 사용

mysql(""" 

SELECT *
FROM bike
WHERE season <> 'spring'
""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-03-21,summer,2011,Mar,0,0,Monday,1,LightRain,0.34,0.3030,0.66,0.3881,2,11,13
1,2011-03-21,summer,2011,Mar,1,0,Monday,1,Cloudy,0.34,0.3030,0.71,0.3881,1,6,7
2,2011-03-21,summer,2011,Mar,2,0,Monday,1,Cloudy,0.34,0.3030,0.71,0.3284,1,5,6
3,2011-03-21,summer,2011,Mar,3,0,Monday,1,Cloudy,0.34,0.3030,0.71,0.3284,0,1,1
4,2011-03-21,summer,2011,Mar,5,0,Monday,1,Clear,0.32,0.3030,0.81,0.2985,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13132,2012-12-20,winter,2012,Dec,19,0,Thursday,1,LightRain,0.34,0.3182,0.71,0.2537,3,115,118
13133,2012-12-20,winter,2012,Dec,20,0,Thursday,1,LightRain,0.34,0.3333,0.76,0.1642,1,49,50
13134,2012-12-20,winter,2012,Dec,21,0,Thursday,1,LightRain,0.34,0.3333,0.76,0.1642,1,25,26
13135,2012-12-20,winter,2012,Dec,22,0,Thursday,1,LightRain,0.34,0.3333,0.87,0.1940,1,20,21
13136,2012-12-20,winter,2012,Dec,23,0,Thursday,1,LightRain,0.40,0.4091,0.82,0.2985,0,13,13

In [11]:
# 비교 연산자 >, >=
# 컬럼을 기준으로 데이터 값보다 큰 경우 사용할 수 있다.
# 숫자 타입의 금액이나 날짜 타입의 날짜를 데이터 값으로 사용할 때 사용

# 23시 이후 대여건에 대한 전체 데이터 확인하기
mysql("""

SELECT *
FROM bike
WHERE hr >= 23
LIMIT 100

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,23,0,Saturday,0,Cloudy,0.46,0.4545,0.88,0.2985,15,24,39
1,2011-01-02,spring,2011,Jan,23,0,Sunday,0,Clear,0.22,0.2273,0.47,0.1642,0,8,8
2,2011-01-03,spring,2011,Jan,23,0,Monday,1,Clear,0.18,0.2121,0.55,0.1045,1,11,12
3,2011-01-04,spring,2011,Jan,23,0,Tuesday,1,Clear,0.20,0.2273,0.69,0.0896,2,9,11
4,2011-01-05,spring,2011,Jan,23,0,Wednesday,1,Clear,0.20,0.2576,0.47,0.0000,1,18,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2011-04-07,summer,2011,Apr,23,0,Thursday,1,Clear,0.38,0.3939,0.76,0.2537,9,45,54
96,2011-04-08,summer,2011,Apr,23,0,Friday,1,Cloudy,0.30,0.2879,0.93,0.2239,4,31,35
97,2011-04-09,summer,2011,Apr,23,0,Saturday,0,Cloudy,0.38,0.3939,0.87,0.0896,12,45,57
98,2011-04-10,summer,2011,Apr,23,0,Sunday,0,Clear,0.46,0.4545,0.88,0.3582,5,27,32
99,2011-04-11,summer,2011,Apr,23,0,Monday,1,LightRain,0.58,0.5455,0.60,0.0000,16,38,54

In [12]:
# 비교 연산자 <, <=
# 컬럼을 기준으로 데이터 값보다 작은 경우에 사용
# 온도 0.2미만 전체 데이터 추출하기

mysql("""

SELECT *
FROM bike
WHERE temp < 0.2
LIMIT 100

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-03,spring,2011,Jan,4,0,Monday,1,Clear,0.16,0.1364,0.47,0.3881,0,1,1
1,2011-01-03,spring,2011,Jan,5,0,Monday,1,Clear,0.16,0.1364,0.47,0.2836,0,3,3
2,2011-01-03,spring,2011,Jan,6,0,Monday,1,Clear,0.14,0.1061,0.50,0.3881,0,30,30
3,2011-01-03,spring,2011,Jan,7,0,Monday,1,Clear,0.14,0.1364,0.50,0.1940,1,63,64
4,2011-01-03,spring,2011,Jan,8,0,Monday,1,Clear,0.14,0.1212,0.50,0.2836,1,153,154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2011-01-11,spring,2011,Jan,1,0,Tuesday,1,Clear,0.14,0.1515,0.59,0.1642,0,3,3
96,2011-01-11,spring,2011,Jan,2,0,Tuesday,1,Cloudy,0.16,0.1515,0.55,0.1940,0,3,3
97,2011-01-11,spring,2011,Jan,5,0,Tuesday,1,Cloudy,0.16,0.1818,0.55,0.1343,0,6,6
98,2011-01-11,spring,2011,Jan,6,0,Tuesday,1,Cloudy,0.16,0.1818,0.55,0.1343,0,27,27
99,2011-01-11,spring,2011,Jan,7,0,Tuesday,1,Cloudy,0.16,0.2273,0.55,0.0000,2,97,99

In [13]:
# 전체 대여 건수가 100건보다 작은 데이터를 추출

mysql(""" 

SELECT *
FROM bike
WHERE cnt < 100

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7005,2012-12-31,spring,2012,Dec,7,0,Monday,1,Clear,0.16,0.1818,0.64,0.1343,2,83,85
7006,2012-12-31,spring,2012,Dec,20,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,8,81,89
7007,2012-12-31,spring,2012,Dec,21,0,Monday,1,Clear,0.26,0.2576,0.60,0.1642,7,83,90
7008,2012-12-31,spring,2012,Dec,22,0,Monday,1,Clear,0.26,0.2727,0.56,0.1343,13,48,61
7009,2012-12-31,spring,2012,Dec,23,0,Monday,1,Clear,0.26,0.2727,0.65,0.1343,12,37,49

# 논리 연산자 사용하기
- 여러가지 조건을 주고 싶을 때 사용
- 논리 연산자를 계속 추가하면 복잡한 조건도 쉽게 필터링할 수 있다.

![image.png](./images/3.png)

## 1. AND 연산자
- 앞의 조건과 뒤의 조건 둘 다 만족한 참인 값인 경우 필터링을 해준다.
- 조건을 계속 추가해야할 때 사용한다.

In [15]:
# bike 테이블에서 2011년도 겨울 시즌의 데이터 조회하기
# yr = 2011 AND season = 'winter'

mysql("""

SELECT *
FROM bike
WHERE yr = 2011
    AND season = 'winter'
LIMIT 100

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-09-23,winter,2011,Sep,0,0,Friday,1,Cloudy,0.62,0.5455,0.94,0.0896,11,41,52
1,2011-09-23,winter,2011,Sep,1,0,Friday,1,Cloudy,0.60,0.5000,1.00,0.0000,2,29,31
2,2011-09-23,winter,2011,Sep,2,0,Friday,1,Cloudy,0.60,0.5000,1.00,0.1045,6,14,20
3,2011-09-23,winter,2011,Sep,3,0,Friday,1,Cloudy,0.60,0.5000,1.00,0.0000,3,5,8
4,2011-09-23,winter,2011,Sep,4,0,Friday,1,LightRain,0.60,0.5000,1.00,0.0000,6,7,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2011-09-26,winter,2011,Sep,23,0,Monday,1,Clear,0.62,0.5455,0.94,0.1343,11,64,75
96,2011-09-27,winter,2011,Sep,0,0,Tuesday,1,Clear,0.62,0.5455,0.94,0.1343,9,28,37
97,2011-09-27,winter,2011,Sep,1,0,Tuesday,1,Clear,0.62,0.5455,0.94,0.1642,4,6,10
98,2011-09-27,winter,2011,Sep,2,0,Tuesday,1,Clear,0.62,0.5455,0.94,0.1045,7,4,11
99,2011-09-27,winter,2011,Sep,3,0,Tuesday,1,Cloudy,0.62,0.5455,0.94,0.0000,5,5,10

In [17]:
# bike 테이블에서 2011년도 봄 시즌의 데이터 조회하기

mysql("""

SELECT *
FROM bike
WHERE yr = 2011
    AND season = 'spring'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2063,2011-12-31,spring,2011,Dec,19,0,Saturday,0,Clear,0.42,0.4242,0.54,0.2239,19,73,92
2064,2011-12-31,spring,2011,Dec,20,0,Saturday,0,Clear,0.42,0.4242,0.54,0.2239,8,63,71
2065,2011-12-31,spring,2011,Dec,21,0,Saturday,0,Clear,0.40,0.4091,0.58,0.1940,2,50,52
2066,2011-12-31,spring,2011,Dec,22,0,Saturday,0,Clear,0.38,0.3939,0.62,0.1343,2,36,38
2067,2011-12-31,spring,2011,Dec,23,0,Saturday,0,Clear,0.36,0.3788,0.66,0.0000,4,27,31

In [18]:
# bike 테이블에서 2011년도 봄시즌의 22시에 발생한 데이터

mysql(""" 

SELECT *
FROM bike
WHERE yr = 2011
    AND season = 'spring'
    AND hr = 22

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,22,0,Saturday,0,Cloudy,0.40,0.4091,0.94,0.2239,11,17,28
1,2011-01-02,spring,2011,Jan,22,0,Sunday,0,Clear,0.24,0.2121,0.44,0.2985,0,9,9
2,2011-01-03,spring,2011,Jan,22,0,Monday,1,Clear,0.14,0.1515,0.69,0.1343,0,20,20
3,2011-01-04,spring,2011,Jan,22,0,Tuesday,1,Clear,0.22,0.2576,0.64,0.0896,1,34,35
4,2011-01-05,spring,2011,Jan,22,0,Wednesday,1,Clear,0.18,0.1970,0.55,0.1343,1,41,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,2011-12-27,spring,2011,Dec,22,0,Tuesday,1,Clear,0.32,0.3333,0.87,0.0896,3,29,32
85,2011-12-28,spring,2011,Dec,22,0,Wednesday,1,Clear,0.22,0.2424,0.44,0.1045,2,31,33
86,2011-12-29,spring,2011,Dec,22,0,Thursday,1,Clear,0.28,0.2879,0.65,0.1343,7,48,55
87,2011-12-30,spring,2011,Dec,22,0,Friday,1,Cloudy,0.34,0.3333,0.71,0.1642,7,78,85
88,2011-12-31,spring,2011,Dec,22,0,Saturday,0,Clear,0.38,0.3939,0.62,0.1343,2,36,38

In [20]:
# bike 테이블에서 2011년도 봄시즌의 일요일에 발생한 데이터
mysql("""

SELECT *
FROM bike
WHERE yr = 2011
    AND season = 'spring'
    AND weekday = 'Sunday'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-02,spring,2011,Jan,0,0,Sunday,0,Cloudy,0.46,0.4545,0.88,0.2985,4,13,17
1,2011-01-02,spring,2011,Jan,1,0,Sunday,0,Cloudy,0.44,0.4394,0.94,0.2537,1,16,17
2,2011-01-02,spring,2011,Jan,2,0,Sunday,0,Cloudy,0.42,0.4242,1.00,0.2836,1,8,9
3,2011-01-02,spring,2011,Jan,3,0,Sunday,0,Cloudy,0.46,0.4545,0.94,0.1940,2,4,6
4,2011-01-02,spring,2011,Jan,4,0,Sunday,0,Cloudy,0.46,0.4545,0.94,0.1940,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,2011-12-25,spring,2011,Dec,19,0,Sunday,0,Clear,0.32,0.3333,0.57,0.1343,2,14,16
299,2011-12-25,spring,2011,Dec,20,0,Sunday,0,Clear,0.32,0.3333,0.49,0.0896,8,18,26
300,2011-12-25,spring,2011,Dec,21,0,Sunday,0,Clear,0.30,0.3030,0.56,0.1343,4,15,19
301,2011-12-25,spring,2011,Dec,22,0,Sunday,0,Clear,0.28,0.2727,0.61,0.1642,2,15,17
302,2011-12-25,spring,2011,Dec,23,0,Sunday,0,Clear,0.26,0.2727,0.65,0.1343,2,14,16

## 2. OR
- 앞의 조건을 만족하거나 뒤의 조건을 만족 즉, 한쪽이라도 참이면 만족시킨 값을 필터링한다.
- 조건을 계속 추가해야할 때 사용한다.

In [22]:
# hr이 10이거나 11인 행 추출

mysql("""

SELECT *
FROM bike
WHERE hr = 10 
      OR hr = 11

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,10,0,Saturday,0,Clear,0.38,0.3939,0.76,0.2537,12,24,36
1,2011-01-01,spring,2011,Jan,11,0,Saturday,0,Clear,0.36,0.3333,0.81,0.2836,26,30,56
2,2011-01-02,spring,2011,Jan,10,0,Sunday,0,Cloudy,0.36,0.3485,0.81,0.2239,7,46,53
3,2011-01-02,spring,2011,Jan,11,0,Sunday,0,Cloudy,0.36,0.3333,0.71,0.2537,16,54,70
4,2011-01-03,spring,2011,Jan,10,0,Monday,1,Clear,0.18,0.1667,0.43,0.2537,11,33,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,2012-12-29,spring,2012,Dec,11,0,Saturday,0,LightRain,0.20,0.2424,0.93,0.0896,7,38,45
1450,2012-12-30,spring,2012,Dec,10,0,Sunday,0,Clear,0.26,0.2121,0.41,0.5821,31,91,122
1451,2012-12-30,spring,2012,Dec,11,0,Sunday,0,Clear,0.26,0.2273,0.41,0.4179,33,103,136
1452,2012-12-31,spring,2012,Dec,10,0,Monday,1,Cloudy,0.20,0.2121,0.69,0.1343,33,87,120
1453,2012-12-31,spring,2012,Dec,11,0,Monday,1,Cloudy,0.22,0.2273,0.60,0.1940,43,114,157

In [25]:
# bike 테이블에서 2011년 또는 봄시즌의 데이터 출력하기
mysql("""

SELECT *
FROM bike
WHERE yr = 2011
      OR season = 'spring'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10814,2012-12-31,spring,2012,Dec,19,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,11,108,119
10815,2012-12-31,spring,2012,Dec,20,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,8,81,89
10816,2012-12-31,spring,2012,Dec,21,0,Monday,1,Clear,0.26,0.2576,0.60,0.1642,7,83,90
10817,2012-12-31,spring,2012,Dec,22,0,Monday,1,Clear,0.26,0.2727,0.56,0.1343,13,48,61
10818,2012-12-31,spring,2012,Dec,23,0,Monday,1,Clear,0.26,0.2727,0.65,0.1343,12,37,49

## 3. IN
- 컬럼이 어떤 값들의 집합에 속한 경우 IN을 사용한다.
- 조회하고자 하는 데이터 값이 여러 개일 떄 사용
- =과 유사하지만 =은 데이터 값 하나를 조건으로 줄 수 있다.
- IN은 데이터 값을 여러 개의 list로 지정할 수 있다.
    - 여러 개 값의 리스트 중 하나의 값이 만족하면 만족하는 결과값을 출력한다.

In [26]:
# N을 사용하여 1월(Jan), 3월(Mar), 5월(May)에 대한 전체 데이터를 추출

mysql("""

SELECT *
FROM bike
WHERE mnth IN ('Jan', 'Mar', 'May')

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4385,2012-05-31,summer,2012,May,19,0,Thursday,1,Clear,0.72,0.6515,0.34,0.1642,104,487,591
4386,2012-05-31,summer,2012,May,20,0,Thursday,1,Clear,0.68,0.6364,0.44,0.1642,88,391,479
4387,2012-05-31,summer,2012,May,21,0,Thursday,1,Clear,0.68,0.6364,0.44,0.1642,41,318,359
4388,2012-05-31,summer,2012,May,22,0,Thursday,1,Clear,0.66,0.6212,0.50,0.1642,43,221,264
4389,2012-05-31,summer,2012,May,23,0,Thursday,1,Clear,0.66,0.6212,0.54,0.2239,26,114,140

In [28]:
# OR로도 동일한 데이터를 추출할 수 있지만 하나의 컬럼에서 같은 인자를 조건으로 줄 때 IN을 사용하는 것이 효율적

mysql("""

SELECT *
FROM bike
WHERE mnth = 'Jan'
OR mnth = 'Mar' 
OR mnth = 'May'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4385,2012-05-31,summer,2012,May,19,0,Thursday,1,Clear,0.72,0.6515,0.34,0.1642,104,487,591
4386,2012-05-31,summer,2012,May,20,0,Thursday,1,Clear,0.68,0.6364,0.44,0.1642,88,391,479
4387,2012-05-31,summer,2012,May,21,0,Thursday,1,Clear,0.68,0.6364,0.44,0.1642,41,318,359
4388,2012-05-31,summer,2012,May,22,0,Thursday,1,Clear,0.66,0.6212,0.50,0.1642,43,221,264
4389,2012-05-31,summer,2012,May,23,0,Thursday,1,Clear,0.66,0.6212,0.54,0.2239,26,114,140

## 4. NOT
- 논리연산자의 의미 반전
- 조건을 부정으로 만들어 부정 연산자라고 한다.
- 선언한 조건에 대해 반대 결과를 반환

In [29]:
# 월(Jan), 3월(Mar), 5월(May)이 아닌 전체 데이터를 추출

mysql("""

SELECT *
FROM bike
WHERE mnth NOT IN ('Jan', 'Mar', 'May')

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-02-01,spring,2011,Feb,0,0,Tuesday,1,Cloudy,0.16,0.1818,0.64,0.1045,2,6,8
1,2011-02-01,spring,2011,Feb,1,0,Tuesday,1,Cloudy,0.16,0.1818,0.69,0.1045,0,3,3
2,2011-02-01,spring,2011,Feb,2,0,Tuesday,1,Cloudy,0.16,0.2273,0.69,0.0000,0,2,2
3,2011-02-01,spring,2011,Feb,3,0,Tuesday,1,Cloudy,0.16,0.2273,0.69,0.0000,0,2,2
4,2011-02-01,spring,2011,Feb,5,0,Tuesday,1,LightRain,0.14,0.2121,0.93,0.0000,0,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12984,2012-12-31,spring,2012,Dec,19,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,11,108,119
12985,2012-12-31,spring,2012,Dec,20,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,8,81,89
12986,2012-12-31,spring,2012,Dec,21,0,Monday,1,Clear,0.26,0.2576,0.60,0.1642,7,83,90
12987,2012-12-31,spring,2012,Dec,22,0,Monday,1,Clear,0.26,0.2727,0.56,0.1343,13,48,61
12988,2012-12-31,spring,2012,Dec,23,0,Monday,1,Clear,0.26,0.2727,0.65,0.1343,12,37,49

In [32]:
# 1월(Jan), 3월(Mar), 5월(May)이 아니고, 전체 대여 건수가 10보다 큰 전체 데이터를 추출
mysql(""" 

SELECT *
FROM bike
WHERE mnth NOT IN ('Jan', 'Mar', 'May')
      AND cnt > 10

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-02-01,spring,2011,Feb,6,0,Tuesday,1,LightRain,0.14,0.2121,0.93,0.0000,0,22,22
1,2011-02-01,spring,2011,Feb,7,0,Tuesday,1,LightRain,0.16,0.2273,0.93,0.0000,0,52,52
2,2011-02-01,spring,2011,Feb,8,0,Tuesday,1,LightRain,0.16,0.2273,0.93,0.0000,3,132,135
3,2011-02-01,spring,2011,Feb,9,0,Tuesday,1,Cloudy,0.16,0.2273,0.93,0.0000,2,114,116
4,2011-02-01,spring,2011,Feb,10,0,Tuesday,1,Cloudy,0.16,0.2273,0.93,0.0000,0,47,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11609,2012-12-31,spring,2012,Dec,19,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,11,108,119
11610,2012-12-31,spring,2012,Dec,20,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,8,81,89
11611,2012-12-31,spring,2012,Dec,21,0,Monday,1,Clear,0.26,0.2576,0.60,0.1642,7,83,90
11612,2012-12-31,spring,2012,Dec,22,0,Monday,1,Clear,0.26,0.2727,0.56,0.1343,13,48,61
11613,2012-12-31,spring,2012,Dec,23,0,Monday,1,Clear,0.26,0.2727,0.65,0.1343,12,37,49

## 5. NULL
- 값이 지정되지 않아 알 수 없는 값
- NULL은 0이나 공백이랑 다르다.

In [33]:
# 날씨 데이터의 값이 NULL값인 데이터를 추출
mysql("""

SELECT *
FROM bike
WHERE weathersit IS NULL

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-02-19,spring,2011,Feb,11,0,Saturday,0,None,0.44,0.4394,0.16,0.5821,47,76,123

In [34]:
# 날씨 데이터의 값이 NULL값이 아닌 전체 데이터를 추출

mysql("""

SELECT *
FROM bike
WHERE weathersit IS NOT NULL

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,spring,2011,Jan,0,0,Saturday,0,Clear,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,spring,2011,Jan,1,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,spring,2011,Jan,2,0,Saturday,0,Clear,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,spring,2011,Jan,3,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,spring,2011,Jan,4,0,Saturday,0,Clear,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17373,2012-12-31,spring,2012,Dec,19,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,11,108,119
17374,2012-12-31,spring,2012,Dec,20,0,Monday,1,Cloudy,0.26,0.2576,0.60,0.1642,8,81,89
17375,2012-12-31,spring,2012,Dec,21,0,Monday,1,Clear,0.26,0.2576,0.60,0.1642,7,83,90
17376,2012-12-31,spring,2012,Dec,22,0,Monday,1,Clear,0.26,0.2727,0.56,0.1343,13,48,61
17377,2012-12-31,spring,2012,Dec,23,0,Monday,1,Clear,0.26,0.2727,0.65,0.1343,12,37,49

## 6. Between A and B
- A와 B 사이에 값이 존재할 때 사용, 주의할 점은 A와 B를 포함한다.
- 두 값의 범위에 해당하는 행을 출력할 때 사용
- 주로 날짜사이에 간격을 줄 때 자주 사용하는 편
- 최소값과 최대값을 지정한 값의 범위 내에 있는 값들을 검색하기 위해 사용
- number Between 3 AND 5와 number>=3 AND number<=5는 동일한 결과를 출력

In [35]:
# 2011년 3월 30일 ~ 31일 사이의 데이터를 확인

mysql(""" 

SELECT *
FROM bike
WHERE dteday Between '2011-03-30' and '2011-03-31'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-03-30,summer,2011,Mar,0,0,Wednesday,1,Cloudy,0.32,0.3485,0.57,0.0000,3,8,11
1,2011-03-30,summer,2011,Mar,1,0,Wednesday,1,Clear,0.32,0.3485,0.39,0.0000,1,9,10
2,2011-03-30,summer,2011,Mar,2,0,Wednesday,1,Cloudy,0.32,0.3485,0.57,0.0000,0,4,4
3,2011-03-30,summer,2011,Mar,3,0,Wednesday,1,Cloudy,0.32,0.3485,0.49,0.0000,0,4,4
4,2011-03-30,summer,2011,Mar,4,0,Wednesday,1,Cloudy,0.32,0.3485,0.57,0.0000,1,0,1
5,2011-03-30,summer,2011,Mar,5,0,Wednesday,1,Cloudy,0.30,0.2879,0.56,0.1940,0,7,7
6,2011-03-30,summer,2011,Mar,6,0,Wednesday,1,Cloudy,0.30,0.3030,0.49,0.1343,4,44,48
7,2011-03-30,summer,2011,Mar,7,0,Wednesday,1,Cloudy,0.32,0.3333,0.45,0.1045,8,128,136
8,2011-03-30,summer,2011,Mar,8,0,Wednesday,1,Cloudy,0.32,0.3182,0.49,0.1642,16,247,263
9,2011-03-30,summer,2011,Mar,9,0,Wednesday,1,Cloudy,0.32,0.3030,0.45,0.2239,7,147,154
10,2011-03-30,summer,2011,Mar,10,0,Wednesday,1,Cloudy,0.34,0.3182,0.46,0.2239,13,51,64
11,2011-03-30,summer,2011,Mar,11,0,Wednesday,1,Cloudy,0.34,0.3182,0.46,0.2537,26,64,90
12,2011-03-30,summer,2011,Mar,12,0,Wednesday,1,Cloudy,0.34,0.3333,0.46,0.1642,15,65,80
13,2011-03-30,summer,2011,Mar,13,0,Wednesday,1,Cloudy,0.36,0.3485,0.46,0.2239,14,84,98
14,2011-03-30,summer,2011,Mar,14,0,Wednesday,1,Cloudy,0.36,0.3333,0.46,0.2985,16,64,80
15,2011-03-30,summer,2011,Mar,15,0,Wednesday,1,LightRain,0.28,0.2576,0.81,0.2985,14,56,70
16,2011-03-30,summer,2011,Mar,16,0,Wednesday,1,LightRain,0.28,0.2727,0.87,0.2537,0,36,36
17,2011-03-30,summer,2011,Mar,17,0,Wednesday,1,LightRain,0.26,0.2727,0.93,0.1045,11,105,116
18,2011-03-30,summer,2011,Mar,18,0,Wednesday,1,Cloudy,0.26,0.2576,0.93,0.2239,6,79,85
19,2011-03-30,summer,2011,Mar,19,0,Wednesday,1,Cloudy,0.26,0.2576,0.93,0.2239,5,67,72
20,2011-03-30,summer,2011,Mar,20,0,Wednesday,1,LightRain,0.24,0.2121,0.93,0.2985,4,40,44
21,2011-03-30,summer,2011,Mar,21,0,Wednesday,1,Cloudy,0.24,0.2273,0.93,0.2537,0,27,27
22,2011-03-30,summer,2011,Mar,22,0,Wednesday,1,LightRain,0.24,0.2273,0.93,0.2239,3,21,24
23,2011-03-30,summer,2011,Mar,23,0,Wednesday,1,LightRain,0.24,0.2121,0.93,0.2836,1,11,12
24,2011-03-31,summer,2011,Mar,0,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2239,0,3,3
25,2011-03-31,summer,2011,Mar,1,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.1940,1,4,5
26,2011-03-31,summer,2011,Mar,2,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.1940,0,5,5
27,2011-03-31,summer,2011,Mar,3,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2239,0,1,1
28,2011-03-31,summer,2011,Mar,4,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2537,0,2,2
29,2011-03-31,summer,2011,Mar,5,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2239,0,8,8
30,2011-03-31,summer,2011,Mar,6,0,Thursday,1,LightRain,0.24,0.2121,0.93,0.2985,2,34,36
31,2011-03-31,summer,2011,Mar,7,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2537,5,87,92
32,2011-03-31,summer,2011,Mar,8,0,Thursday,1,Cloudy,0.24,0.2273,1.00,0.2537,7,185,192
33,2011-03-31,summer,2011,Mar,9,0,Thursday,1,LightRain,0.26,0.2424,0.93,0.2537,6,126,132
34,2011-03-31,summer,2011,Mar,10,0,Thursday,1,LightRain,0.26,0.2424,0.93,0.2537,15,54,69
35,2011-03-31,summer,2011,Mar,11,0,Thursday,1,LightRain,0.28,0.2727,0.93,0.1940,6,52,58
36,2011-03-31,summer,2011,Mar,12,0,Thursday,1,LightRain,0.28,0.2727,0.93,0.1940,17,73,90
37,2011-03-31,summer,2011,Mar,13,0,Thursday,1,LightRain,0.30,0.3030,0.87,0.1343,13,55,68
38,2011-03-31,summer,2011,Mar,14,0,Thursday,1,LightRain,0.30,0.3030,0.87,0.1343,27,49,76
39,2011-03-31,summer,2011,Mar,15,0,Thursday,1,LightRain,0.30,0.2727,0.87,0.2985,4,61,65
40,2011-03-31,summer,2011,Mar,16,0,Thursday,1,Cloudy,0.30,0.2879,0.87,0.2537,13,72,85
41,2011-03-31,summer,2011,Mar,17,0,Thursday,1,Cloudy,0.30,0.2879,0.87,0.2537,15,153,168
42,2011-03-31,summer,2011,Mar,18,0,Thursday,1,Cloudy,0.30,0.3030,0.87,0.1343,12,165,177
43,2011-03-31,summer,2011,Mar,19,0,Thursday,1,Cloudy,0.30,0.3030,0.87,0.1343,12,118,130
44,2011-03-31,summer,2011,Mar,20,0,Thursday,1,LightRain,0.28,0.2576,0.93,0.2836,6,79,85
45,2011-03-31,summer,2011,Mar,21,0,Thursday,1,Cloudy,0.28,0.2727,0.93,0.1642,7,53,60
46,2011-03-31,summer,2011,Mar,22,0,Thursday,1,LightRain,0.28,0.2727,0.93,0.2537,7,44,51
47,2011-03-31,summer,2011,Mar,23,0,Thursday,1,LightRain,0.26,0.2576,1.00,0.1642,4,23,27

In [36]:
# 비교 연산자를 사용하여 검색

mysql("""

SELECT *
FROM bike
WHERE dteday >= '2011-03-30' 
      AND dteday <= '2011-03-31'

""")

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-03-30,summer,2011,Mar,0,0,Wednesday,1,Cloudy,0.32,0.3485,0.57,0.0000,3,8,11
1,2011-03-30,summer,2011,Mar,1,0,Wednesday,1,Clear,0.32,0.3485,0.39,0.0000,1,9,10
2,2011-03-30,summer,2011,Mar,2,0,Wednesday,1,Cloudy,0.32,0.3485,0.57,0.0000,0,4,4
3,2011-03-30,summer,2011,Mar,3,0,Wednesday,1,Cloudy,0.32,0.3485,0.49,0.0000,0,4,4
4,2011-03-30,summer,2011,Mar,4,0,Wednesday,1,Cloudy,0.32,0.3485,0.57,0.0000,1,0,1
5,2011-03-30,summer,2011,Mar,5,0,Wednesday,1,Cloudy,0.30,0.2879,0.56,0.1940,0,7,7
6,2011-03-30,summer,2011,Mar,6,0,Wednesday,1,Cloudy,0.30,0.3030,0.49,0.1343,4,44,48
7,2011-03-30,summer,2011,Mar,7,0,Wednesday,1,Cloudy,0.32,0.3333,0.45,0.1045,8,128,136
8,2011-03-30,summer,2011,Mar,8,0,Wednesday,1,Cloudy,0.32,0.3182,0.49,0.1642,16,247,263
9,2011-03-30,summer,2011,Mar,9,0,Wednesday,1,Cloudy,0.32,0.3030,0.45,0.2239,7,147,154
10,2011-03-30,summer,2011,Mar,10,0,Wednesday,1,Cloudy,0.34,0.3182,0.46,0.2239,13,51,64
11,2011-03-30,summer,2011,Mar,11,0,Wednesday,1,Cloudy,0.34,0.3182,0.46,0.2537,26,64,90
12,2011-03-30,summer,2011,Mar,12,0,Wednesday,1,Cloudy,0.34,0.3333,0.46,0.1642,15,65,80
13,2011-03-30,summer,2011,Mar,13,0,Wednesday,1,Cloudy,0.36,0.3485,0.46,0.2239,14,84,98
14,2011-03-30,summer,2011,Mar,14,0,Wednesday,1,Cloudy,0.36,0.3333,0.46,0.2985,16,64,80
15,2011-03-30,summer,2011,Mar,15,0,Wednesday,1,LightRain,0.28,0.2576,0.81,0.2985,14,56,70
16,2011-03-30,summer,2011,Mar,16,0,Wednesday,1,LightRain,0.28,0.2727,0.87,0.2537,0,36,36
17,2011-03-30,summer,2011,Mar,17,0,Wednesday,1,LightRain,0.26,0.2727,0.93,0.1045,11,105,116
18,2011-03-30,summer,2011,Mar,18,0,Wednesday,1,Cloudy,0.26,0.2576,0.93,0.2239,6,79,85
19,2011-03-30,summer,2011,Mar,19,0,Wednesday,1,Cloudy,0.26,0.2576,0.93,0.2239,5,67,72
20,2011-03-30,summer,2011,Mar,20,0,Wednesday,1,LightRain,0.24,0.2121,0.93,0.2985,4,40,44
21,2011-03-30,summer,2011,Mar,21,0,Wednesday,1,Cloudy,0.24,0.2273,0.93,0.2537,0,27,27
22,2011-03-30,summer,2011,Mar,22,0,Wednesday,1,LightRain,0.24,0.2273,0.93,0.2239,3,21,24
23,2011-03-30,summer,2011,Mar,23,0,Wednesday,1,LightRain,0.24,0.2121,0.93,0.2836,1,11,12
24,2011-03-31,summer,2011,Mar,0,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2239,0,3,3
25,2011-03-31,summer,2011,Mar,1,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.1940,1,4,5
26,2011-03-31,summer,2011,Mar,2,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.1940,0,5,5
27,2011-03-31,summer,2011,Mar,3,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2239,0,1,1
28,2011-03-31,summer,2011,Mar,4,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2537,0,2,2
29,2011-03-31,summer,2011,Mar,5,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2239,0,8,8
30,2011-03-31,summer,2011,Mar,6,0,Thursday,1,LightRain,0.24,0.2121,0.93,0.2985,2,34,36
31,2011-03-31,summer,2011,Mar,7,0,Thursday,1,LightRain,0.24,0.2273,0.93,0.2537,5,87,92
32,2011-03-31,summer,2011,Mar,8,0,Thursday,1,Cloudy,0.24,0.2273,1.00,0.2537,7,185,192
33,2011-03-31,summer,2011,Mar,9,0,Thursday,1,LightRain,0.26,0.2424,0.93,0.2537,6,126,132
34,2011-03-31,summer,2011,Mar,10,0,Thursday,1,LightRain,0.26,0.2424,0.93,0.2537,15,54,69
35,2011-03-31,summer,2011,Mar,11,0,Thursday,1,LightRain,0.28,0.2727,0.93,0.1940,6,52,58
36,2011-03-31,summer,2011,Mar,12,0,Thursday,1,LightRain,0.28,0.2727,0.93,0.1940,17,73,90
37,2011-03-31,summer,2011,Mar,13,0,Thursday,1,LightRain,0.30,0.3030,0.87,0.1343,13,55,68
38,2011-03-31,summer,2011,Mar,14,0,Thursday,1,LightRain,0.30,0.3030,0.87,0.1343,27,49,76
39,2011-03-31,summer,2011,Mar,15,0,Thursday,1,LightRain,0.30,0.2727,0.87,0.2985,4,61,65
40,2011-03-31,summer,2011,Mar,16,0,Thursday,1,Cloudy,0.30,0.2879,0.87,0.2537,13,72,85
41,2011-03-31,summer,2011,Mar,17,0,Thursday,1,Cloudy,0.30,0.2879,0.87,0.2537,15,153,168
42,2011-03-31,summer,2011,Mar,18,0,Thursday,1,Cloudy,0.30,0.3030,0.87,0.1343,12,165,177
43,2011-03-31,summer,2011,Mar,19,0,Thursday,1,Cloudy,0.30,0.3030,0.87,0.1343,12,118,130
44,2011-03-31,summer,2011,Mar,20,0,Thursday,1,LightRain,0.28,0.2576,0.93,0.2836,6,79,85
45,2011-03-31,summer,2011,Mar,21,0,Thursday,1,Cloudy,0.28,0.2727,0.93,0.1642,7,53,60
46,2011-03-31,summer,2011,Mar,22,0,Thursday,1,LightRain,0.28,0.2727,0.93,0.2537,7,44,51
47,2011-03-31,summer,2011,Mar,23,0,Thursday,1,LightRain,0.26,0.2576,1.00,0.1642,4,23,27

# 산술 연산자 사용하기

## 산술연산자
- 데이터값을 계산할 때 사용
- 산술연산자는 +, -, *, / 등이 있다. (우선 순위: () > *, / > +,-)
- SELECT, WHERE 문에서 사용
- 문자열 혹은 날짜타입 데이터에 산술연산자를 적용하면 원하지 않는 값을 얻게될 수 있다.
- 실무에서 많이 쓰이며 비즈니스를 위한 다양한 리포트를 작성할 때 필수적으로 사용
    
> 주의: 위의 코드는 DBMS(Database Management system)에 따라 실행했을 때 에러가 날 수 있기 때문에     
> 날짜나 문자 타입의 경우에는 산술 연산자를 사용하지 않는 것이 좋습니다.

In [37]:
# dteday 값에 2를 더하고, weekday에 3을 더해보기

mysql("""  

SELECT dteday, dteday + 2, weekday , weekday + 3
FROM bike

""")

           dteday  dteday + 2   weekday  weekday + 3
0      2011-01-01        2013  Saturday            3
1      2011-01-01        2013  Saturday            3
2      2011-01-01        2013  Saturday            3
3      2011-01-01        2013  Saturday            3
4      2011-01-01        2013  Saturday            3
...           ...         ...       ...          ...
17374  2012-12-31        2014    Monday            3
17375  2012-12-31        2014    Monday            3
17376  2012-12-31        2014    Monday            3
17377  2012-12-31        2014    Monday            3
17378  2012-12-31        2014    Monday            3

[17379 rows x 4 columns]

In [38]:
# 온도(temp)에 +2, -2, *2, /2 추가해보기

mysql("""
 
SELECT temp
    , temp + 2 
    , temp - 2 
    , temp * 2 
    , temp / 2 
FROM bike

""")

       temp  temp + 2  temp - 2  temp * 2  temp / 2
0      0.24      2.24     -1.76      0.48      0.12
1      0.22      2.22     -1.78      0.44      0.11
2      0.22      2.22     -1.78      0.44      0.11
3      0.24      2.24     -1.76      0.48      0.12
4      0.24      2.24     -1.76      0.48      0.12
...     ...       ...       ...       ...       ...
17374  0.26      2.26     -1.74      0.52      0.13
17375  0.26      2.26     -1.74      0.52      0.13
17376  0.26      2.26     -1.74      0.52      0.13
17377  0.26      2.26     -1.74      0.52      0.13
17378  0.26      2.26     -1.74      0.52      0.13

[17379 rows x 5 columns]